name: workflow1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'dev-**'
      - 'features/**'
  paths-ignore:
    - '.github/workflows/**'

jobs:
  info:
    name: Get Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display repository info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
