name: Workflo1

on:
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint

  test:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm test
