name: workflow1
on: 
  push:
    branch:
      - main
jobs:
  info:
    name: Get Code
    runs-on: ubuntu-latest
    steps:
      - name: Display repository info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"